# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  go:
    docker:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    steps:
      - setup_remote_docker:
          version: 20.10.2 #19.03.13
          docker_layer_caching: true

      - run: docker-compose run sys

workflows:
  welcome:
    jobs:
      - go

